services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./prestashop_8.2.1:/app
      - ./nginx-lemp/vhost-nginx.conf:/etc/nginx/conf.d/vhost-nginx.conf
      - ./certs:/etc/ssl/certs
    env_file:
      - .env.dev
    networks:
      redelamplemp:
        aliases:
          - test.lemp
  phpserver:
    build: ./php-lemp
    volumes:
      - ./prestashop_8.2.1:/app
    env_file:
      - .env.dev
    networks:
      - redelamplemp
      
  basededatos:
    image: mysql:latest
    env_file:
      - .env.dev
    volumes:
      - datos:/var/lib/mysql
    networks:
      redelamplemp:

  cliente:
    hostname: cliente
    image: brunosct/debian12-cliente-firefox
    networks:
      - redelamplemp
    environment:
    - DISPLAY=host.docker.internal:0
    volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix  
volumes:
  datos:
networks:
  redelamplemp: