FROM debian:12


#Instalar paquetes necesarios (php-fpm extensions php)
# RUN apt update && apt install -y \
#     curl \
#     wget \
#     git \
#     && rm -rf /var/lib/apt/lists/* /var/cache/apt/*

#Instalar composer

#Instalar ferramentas npm se son necesarias

#Instrucción para que o contedor escoite nun porto e non nun socket

EXPOSE

#Instruciónn para que o servizo php-fpm se inicie
CMD ["..."]