<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLCqQo7O\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLCqQo7O/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerLCqQo7O.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerLCqQo7O\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerLCqQo7O\appAppKernelProdContainer([
    'container.build_hash' => 'LCqQo7O',
    'container.build_id' => 'c050806e',
    'container.build_time' => 1742134268,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLCqQo7O');
