<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDaLh4DP\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDaLh4DP/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerDaLh4DP.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerDaLh4DP\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerDaLh4DP\appAppKernelProdContainer([
    'container.build_hash' => 'DaLh4DP',
    'container.build_id' => '9e514978',
    'container.build_time' => 1742088483,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDaLh4DP');
