FROM debian:12


#Instalar paquetes necesarios (apache php extensions php)
# RUN apt update && apt install -y \
#     curl \
#     wget \
#     git \
#     && rm -rf /var/lib/apt/lists/* /var/cache/apt/*

#Activar módulos de apache

#Instalar composer

#Instalar ferramentas npm se son necesarias


EXPOSE

#Instrución para arrancar apache
CMD ["..."]